name: Python package

on:
  push:
    branches: [ main ]  # Remplacez 'main' par la branche que vous utilisez
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]  # Utiliser uniquement la dernière version de Python

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]  # Installer votre package en mode editable avec les dépendances de dev

    - name: Run tests
      env:
        KEY: ${{ secrets.KEY }}
        IV: ${{ secrets.IV }}
      run: |
        pytest
